[package]
name = "Recursive_Grep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
thiserror = "1.0" 
colored = "2.0.0"